### ISSUE TITLE
console.log in release build

### ISSUE THREAD

**Issue by squareborg** [dev-bjoern/react-transition-value#1]
Hey, thanks for the package, it appears you left a couple console.log() in the build on [here](https://github.com/dev-bjoern/react-transition-value/blob/3ba98f92f65ac78188451ade7d89bc5acec00b4a/src/lib/useTransitionValue.tsx#L108)

**Comment by axelmy318** [comment]
Hi, could you please fix it... I'd like to use the package but it makes it very annoying for production

**Comment by dev-bjoern** [comment]
This is now fixed and published on npm.
